[workspace]
resolver = "2"
members = [
	"roq",
	"roq_derive"
]

[package]
name = "roq_examples"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
roq = { path = "./roq" }
roq_derive = { path = "./roq_derive" }

[dev-dependencies]
shiba = "0.1.1"

